// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Account struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	Currency  string
	CreatedAt pgtype.Timestamptz
}

type Posting struct {
	ID            uuid.UUID
	TransactionID uuid.UUID
	AccountID     uuid.UUID
	Amount        pgtype.Numeric
	CreatedAt     pgtype.Timestamptz
}

type Transaction struct {
	ID             uuid.UUID
	IdempotencyKey string
	Status         string
	Description    pgtype.Text
	CreatedAt      pgtype.Timestamptz
}

type User struct {
	ID           uuid.UUID
	Email        string
	PasswordHash string
	KycStatus    string
	CreatedAt    pgtype.Timestamptz
}
