// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createPosting = `-- name: CreatePosting :exec
INSERT INTO postings (transaction_id, account_id, amount)
VALUES ($1, $2, $3)
`

type CreatePostingParams struct {
	TransactionID uuid.UUID
	AccountID     uuid.UUID
	Amount        pgtype.Numeric
}

func (q *Queries) CreatePosting(ctx context.Context, arg CreatePostingParams) error {
	_, err := q.db.Exec(ctx, createPosting, arg.TransactionID, arg.AccountID, arg.Amount)
	return err
}

const createTransaction = `-- name: CreateTransaction :one
INSERT INTO transactions (idempotency_key, status, description)
VALUES ($1, $2, $3)
RETURNING id, idempotency_key, status, description, created_at
`

type CreateTransactionParams struct {
	IdempotencyKey string
	Status         string
	Description    pgtype.Text
}

func (q *Queries) CreateTransaction(ctx context.Context, arg CreateTransactionParams) (Transaction, error) {
	row := q.db.QueryRow(ctx, createTransaction, arg.IdempotencyKey, arg.Status, arg.Description)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.IdempotencyKey,
		&i.Status,
		&i.Description,
		&i.CreatedAt,
	)
	return i, err
}

const getAccountForUpdate = `-- name: GetAccountForUpdate :one
SELECT id, user_id, currency, created_at FROM accounts
WHERE id = $1 FOR UPDATE
`

// Verrouille la ligne du compte pour empêcher les modifications concurrentes (Anti-Race Condition)
func (q *Queries) GetAccountForUpdate(ctx context.Context, id uuid.UUID) (Account, error) {
	row := q.db.QueryRow(ctx, getAccountForUpdate, id)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Currency,
		&i.CreatedAt,
	)
	return i, err
}

const getBalance = `-- name: GetBalance :one
SELECT COALESCE(SUM(amount), 0)::numeric AS balance
FROM postings
WHERE account_id = $1
`

// Calcule le solde exact en temps réel basé sur le grand livre
func (q *Queries) GetBalance(ctx context.Context, accountID uuid.UUID) (pgtype.Numeric, error) {
	row := q.db.QueryRow(ctx, getBalance, accountID)
	var balance pgtype.Numeric
	err := row.Scan(&balance)
	return balance, err
}

const updateTransactionStatus = `-- name: UpdateTransactionStatus :exec
UPDATE transactions
SET status = $2
WHERE id = $1
`

type UpdateTransactionStatusParams struct {
	ID     uuid.UUID
	Status string
}

func (q *Queries) UpdateTransactionStatus(ctx context.Context, arg UpdateTransactionStatusParams) error {
	_, err := q.db.Exec(ctx, updateTransactionStatus, arg.ID, arg.Status)
	return err
}
